// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueqobngtkohhhpqstadr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcW9ibmd0a29oaGhwcXN0YWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNTQyODMsImV4cCI6MjA2ODczMDI4M30.QFukREtvlPUD9LuboofRTF_JHRftU72qKPMMHcZfs7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});